version: "3.8"

services:
  app:
    build: .
    container_name: image-verification-service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "7000:8000"
    volumes:
      - "D:/Python/image-verification-service:/app"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    restart: unless-stopped
